### ISSUE TITLE
Publish v1.0.0

### ISSUE THREAD

**Issue by sm2017** [debutdeveloper/sms_retriever#14]
In the https://github.com/lakhwinderdebut/sms_retriever/blob/master/pubspec.yaml#L3 version is 1.0.0 but in https://pub.dev/packages/sms_retriever version is 0.0.2
So, Please publish latest version to the pub.dev

**Comment by andzejsw** [comment]
Should be closed, since v1.0.0 published in https://pub.dev/packages/sms_retriever
