### ISSUE TITLE
 MissingPluginException

### ISSUE THREAD

**Issue by nerocil** [debutdeveloper/sms_retriever#8]
No implementation found for method startListening on channel sms_retriever

I try to run example code and this error throwing

E/libPowerStretch(12564): LUCID Battery Level = 44% Battery Temp = -100 Cpu Temp = -100
E/flutter (12564): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startListening on channel sms_retriever)
E/flutter (12564): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (12564): <asynchronous suspension>
E/flutter (12564): #1      SmsRetriever.startListening (package:sms_retriever/sms_retriever.dart:9:43)
E/flutter (12564): #2      _MyAppState.build.<anonymous closure> (package:smspro/main.dart:49:55)
E/flutter (12564): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (12564): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (12564): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12564): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (12564): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (12564): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (12564): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (12564): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (12564): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (12564): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12564): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (12564): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (12564): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (12564): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12564): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12564): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12564): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12564): #20     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (12564): #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (12564): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (12564): #23     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (12564): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (12564): 
D/Surface (12564): Surface::disconnect(this=0x8e47c800,api=1)
D/Surface (12564): Surface::disconnect(this=0x8e47c800,api=-1)
D/FlutterView(12564): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@6a49f84
V/PhoneWindow(12564): DecorView setVisiblity: visibility = 4, Parent = ViewRoot{83cc197 com.joseph2prosper.smspro/com.joseph2prosper.smspro.MainActivity,ident = 0}, this = DecorView@4129531[MainActivity]
D/Surface (12564): Surface::disconnect(this=0x8e47c000,api=1)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by aman0408** [comment]
This would have happened when you added the package and them hot restarted/reloaded the application. Try stopping and rebuilding it.
